import json
import re
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


class StandaloneLauncherContractTests(unittest.TestCase):
    def read(self, path):
        return (ROOT / path).read_text(encoding="utf-8")

    def test_launcher_is_separate_api29_java_module(self):
        settings = self.read("settings.gradle.kts")
        gradle = self.read("launcher/build.gradle.kts")
        manifest = self.read("launcher/src/main/AndroidManifest.xml")
        self.assertIn('include(":launcher")', settings)
        self.assertIn("compileSdk = 29", gradle)
        self.assertIn("minSdk = 29", gradle)
        self.assertIn("targetSdk = 29", gradle)
        self.assertIn("sourceCompatibility = JavaVersion.VERSION_1_8", gradle)
        self.assertIn("targetCompatibility = JavaVersion.VERSION_1_8", gradle)
        self.assertIn('android:name=".HomeActivity"', manifest)
        self.assertIn('android.intent.category.HOME', manifest)
        self.assertIn('android.intent.category.DEFAULT', manifest)
        self.assertIn('android:name=".MediaListenerService"', manifest)
        self.assertIn('android.permission.BIND_NOTIFICATION_LISTENER_SERVICE', manifest)

    def test_home_alias_is_opt_in_and_dofun_is_not_impersonated(self):
        manifest = self.read("launcher/src/main/AndroidManifest.xml")
        home = self.read("launcher/src/main/java/com/cbkii/ts18launcher/HomeMode.java")
        installer = self.read("scripts/termux/install-standalone-launcher.sh")
        self.assertIn('android:enabled="false"', manifest)
        self.assertIn('android:targetActivity=".LauncherActivity"', manifest)
        self.assertIn("setComponentEnabledSetting", home)
        self.assertIn("pm enable", installer)
        self.assertIn("com.dofun.variety", installer)
        self.assertNotIn("pm disable com.dofun.variety", installer)
        self.assertNotIn("pm uninstall com.dofun.variety", installer)

    def test_launcher_runtime_stays_small_and_single_authority(self):
        gradle = self.read("launcher/build.gradle.kts")
        manifest = self.read("launcher/src/main/AndroidManifest.xml")
        launcher_java = "\n".join(
            path.read_text(encoding="utf-8")
            for path in (ROOT / "launcher/src/main/java").rglob("*.java")
        )
        self.assertNotIn("androidx", gradle)
        self.assertNotIn("kotlin", gradle.lower())
        self.assertNotIn("MediaSession(", launcher_java)
        self.assertNotIn("requestAudioFocus", launcher_java)
        self.assertNotIn("WAKE_LOCK", manifest)
        self.assertNotIn("RECEIVE_BOOT_COMPLETED", manifest)

    def test_leaflet_map_is_local_feature_rich_and_tile_networking_is_native(self):
        html = self.read("launcher/src/main/assets/map/index.html")
        panel = self.read("launcher/src/main/java/com/cbkii/ts18launcher/MapPanel.java")
        broker = self.read("launcher/src/main/java/com/cbkii/ts18launcher/TileBroker.java")
        policy = self.read("launcher/src/main/java/com/cbkii/ts18launcher/ExperimentalMapPolicy.java")
        fetcher = self.read("tools/fetch_leaflet.py")
        self.assertIn("db49d009c841f5ca34a888c96511ae936fd9f5533e90d8b2c4d57596f4e5641a", fetcher)
        self.assertIn("a7837102824184820dfa198d1ebcd109ff6d0ff9a2672a074b9a1b4d147d04c6", fetcher)
        self.assertIn('vendor/leaflet.js', html)
        self.assertIn('vendor/leaflet.css', html)
        self.assertIn('L.map("map"', html)
        self.assertIn('L.tileLayer("https://tile.openstreetmap.org/{z}/{x}/{y}.png"', html)
        self.assertIn("touchZoom:true", html)
        self.assertIn("doubleClickZoom:true", html)
        self.assertIn("inertia:true", html)
        self.assertIn("L.circle", html)
        self.assertIn("vehicle-bearing", html)
        self.assertIn("setLocation", html)
        self.assertIn("map.panTo", html)
        self.assertIn("setMapAppearance", html)
        self.assertIn('follow?"follow":"free"', html)
        self.assertIn("TileBroker.isTileUri", panel)
        self.assertIn("tileBroker.intercept(uri)", panel)
        self.assertIn("mapControlsEnabled", panel)
        self.assertIn("AppearanceController.resolvedMode", panel)
        self.assertIn('"Map offline"', panel)
        self.assertIn("boolean controlsRight = !railRight", panel)
        self.assertNotIn("openNavigation", panel)
        self.assertIn('TILE_HOST = "tile.openstreetmap.org"', broker)
        self.assertIn("FALLBACK_CACHE_TTL_MS", broker)
        self.assertIn("MAX_CACHE_BYTES = 64L * 1024L * 1024L", broker)
        self.assertIn('setRequestProperty("User-Agent", userAgent)', broker)
        self.assertIn('setRequestProperty("If-None-Match"', broker)
        self.assertIn('setRequestProperty("If-Modified-Since"', broker)
        self.assertIn("HttpURLConnection.HTTP_NOT_MODIFIED", broker)
        self.assertIn("staleOrError", broker)
        self.assertIn("LocationManager.GPS_PROVIDER", panel)
        self.assertNotIn("LocationManager.NETWORK_PROVIDER", panel)
        self.assertIn("removeUpdates(this)", panel)
        self.assertNotIn("addJavascriptInterface", panel)
        self.assertNotIn("setAllowUniversalAccessFromFileURLs(true)", panel)
        self.assertNotIn("http://", panel + broker + html)
        self.assertIn("if (!LauncherPrefs.prefs(context).contains(LauncherPrefs.KEY_MAP_ENABLED)) return false", policy)
        self.assertIn("return LauncherPrefs.mapEnabled(context)", policy)

    def test_home_has_fixed_endpoints_optional_weighted_middle_and_navigation_handoff(self):
        prefs = self.read("launcher/src/main/java/com/cbkii/ts18launcher/LauncherPrefs.java")
        personal = self.read("launcher/src/main/java/com/cbkii/ts18launcher/UiPersonalizationPrefs.java")
        launcher = self.read("launcher/src/main/java/com/cbkii/ts18launcher/LauncherActivity.java")
        roles = self.read("launcher/src/main/java/com/cbkii/ts18launcher/RoleIconCatalog.java")
        drawer = self.read("launcher/src/main/java/com/cbkii/ts18launcher/AppDrawerPanel.java")
        nav = self.read("launcher/src/main/java/com/cbkii/ts18launcher/NavigationProvider.java")
        self.assertIn("KEY_QUICK_1", prefs)
        self.assertIn("KEY_QUICK_6", prefs)
        self.assertIn("KEY_QUICK_COUNT", prefs)
        self.assertIn("KEY_RAIL_POSITION", prefs)
        self.assertIn("KEY_DRAWER_QUICK_5", prefs)
        self.assertIn("QUICK_ROLE_KEYS", prefs)
        self.assertIn("Math.max(3, Math.min(6, value))", prefs)
        self.assertIn("KEY_HOME_SHORTCUTS_ENABLED", personal)
        self.assertIn("MAX_QUICK_SLOTS = 6", launcher)
        self.assertIn("ImageButton[] quickButtons", launcher)
        self.assertIn("FrameLayout[] quickCells", launcher)
        self.assertLess(launcher.index("rail.addView(appsButton"), launcher.index("rail.addView(quickRail"))
        self.assertLess(launcher.index("rail.addView(quickRail"), launcher.index("rail.addView(navigationButton"))
        self.assertIn("new LinearLayout.LayoutParams(\n                    LinearLayout.LayoutParams.MATCH_PARENT, 0, 1f)", launcher)
        self.assertIn("homeShortcutsEnabled(this)", launcher)
        self.assertIn("case 0: return SETTINGS", roles)
        self.assertIn("styleRailButton(this, navigationButton, true)", launcher)
        self.assertIn("LauncherPrefs.railOnRight(this)", launcher)
        self.assertIn("AppDrawerPanel", launcher)
        self.assertIn("toggleAppDrawer()", launcher)
        self.assertIn("mapPanel.stop()", launcher)
        self.assertIn("mapPanel.resumeWebView()", launcher)
        self.assertIn("GridView", drawer)
        self.assertIn('search.setHint("Search apps")', drawer)
        self.assertIn("VoiceSearch.available(activity)", drawer)
        self.assertIn("DRAWER_QUICK_KEYS", drawer)
        self.assertIn("R.drawable.ic_settings", drawer)
        self.assertIn("R.drawable.ic_close", drawer)
        self.assertIn("NavigationProvider.open", launcher)
        self.assertIn('GOOGLE_MAPS = "com.google.android.apps.maps"', nav)
        self.assertIn('WAZE = "com.waze"', nav)
        self.assertIn('ORGANIC_MAPS = "app.organicmaps"', nav)
        self.assertIn('OSMAND_PLUS = "net.osmand.plus"', nav)
        self.assertIn("geo:", nav)
        self.assertIn("waze://", nav)

    def test_automotive_ui_uses_local_vectors_gradients_semantic_dimensions_and_inert_date(self):
        launcher = self.read("launcher/src/main/java/com/cbkii/ts18launcher/LauncherActivity.java")
        metadata = self.read("launcher/src/main/java/com/cbkii/ts18launcher/MediaMetadataView.java")
        ui = self.read("launcher/src/main/java/com/cbkii/ts18launcher/AutomotiveUi.java")
        geometry = self.read("launcher/src/main/java/com/cbkii/ts18launcher/Ts18Geometry.java")
        dimens = self.read("launcher/src/main/res/values/dimens.xml")
        drawables = {path.name for path in (ROOT / "launcher/src/main/res/drawable").glob("*.xml")}
        for required in (
            "ic_navigation.xml", "ic_radio.xml", "ic_music.xml", "ic_bluetooth.xml",
            "ic_apps.xml", "ic_settings.xml", "ic_previous.xml", "ic_play.xml",
            "ic_pause.xml", "ic_next.xml", "ic_zoom_in.xml", "ic_zoom_out.xml",
            "ic_my_location.xml", "ic_close.xml", "ic_search.xml", "ic_mic.xml",
            "ic_phone.xml", "ic_star.xml", "ic_utility.xml", "ic_shortcut.xml",
            "ic_car.xml", "ic_map.xml", "ic_route.xml", "ic_equalizer.xml",
            "ic_podcast.xml", "ic_usb.xml", "ic_folder.xml", "ic_wifi.xml",
            "ic_download.xml", "ic_volume.xml", "ic_power.xml", "ic_dashboard.xml",
            "ic_lightbulb.xml", "ic_notifications.xml", "ic_palette.xml",
        ):
            self.assertIn(required, drawables)
        self.assertIn("HOTSEAT_WIDTH = 96", geometry)
        self.assertIn("STRIP_HEIGHT = 88", geometry)
        self.assertIn("DATE_WIDTH = 128", geometry)
        for token in (
            "ui_metadata_text", "ui_metadata_secondary_text", "ui_drawer_icon", "ui_settings_row_height",
            "driver_target_min", "driver_target_primary", "driver_gap", "driver_gap_large",
            "ui_play_visual", "ui_icon_button_padding", "ui_corner_radius", "ui_settings_shortcut_editor_height",
        ):
            self.assertIn(token, dimens)
        self.assertIn("STATE_CROSSFADE_MS = 120L", ui)
        self.assertIn("FEEDBACK_MS = 140L", ui)
        self.assertIn("PANEL_REVEAL_MS = 160L", ui)
        self.assertIn("DRAWER_MS = 180L", ui)
        self.assertIn("mediaGroupBackground", ui)
        self.assertIn("subtleTransportBackground", ui)
        self.assertIn("GradientDrawable.Orientation", ui)
        self.assertIn("state_focused", ui)
        self.assertIn("state_pressed", ui)
        self.assertIn("linkVertical", ui)
        self.assertIn("linkHorizontal", ui)
        self.assertIn("MediaMetadataView", launcher)
        self.assertIn("SlowMarqueeTextView", metadata)
        self.assertIn("lastPrimary", metadata)
        self.assertIn("safeTitle.equals(lastPrimary)", metadata)
        self.assertIn("setIconWithCrossfade", launcher)
        self.assertIn("dateView.setBackgroundColor(android.graphics.Color.TRANSPARENT)", launcher)
        self.assertIn("dateView.setFocusable(false)", launcher)
        self.assertIn("dateView.setClickable(false)", launcher)
        self.assertNotIn("dateView.setOnClickListener", launcher)

    def test_settings_cover_shortcut_editor_palette_warmup_and_advanced_home(self):
        settings = self.read("launcher/src/main/java/com/cbkii/ts18launcher/SettingsActivity.java")
        editor = self.read("launcher/src/main/java/com/cbkii/ts18launcher/ShortcutEditorView.java")
        palette = self.read("launcher/src/main/java/com/cbkii/ts18launcher/AccentPaletteRow.java")
        picker = self.read("launcher/src/main/java/com/cbkii/ts18launcher/AppDrawerActivity.java")
        self.assertIn("new Switch(this)", settings)
        self.assertIn('addSection("Appearance")', settings)
        self.assertIn('addSection("Advanced HOME / recovery")', settings)
        self.assertIn('"Map controls"', settings)
        self.assertIn('"Experimental Leaflet map"', settings)
        self.assertIn('"Display appearance"', settings)
        self.assertIn('"Auto appearance source"', settings)
        self.assertIn('"Rail position"', settings)
        self.assertIn('"Show HOME quick shortcuts"', settings)
        self.assertIn('"Shortcut count"', settings)
        self.assertIn("if (homeShortcuts)", settings)
        self.assertIn('"Radio / Music sides"', settings)
        self.assertIn('"Warm media sources on HOME start"', settings)
        self.assertIn('editorCell("App"', editor)
        self.assertIn('editorCell("Icon"', editor)
        self.assertIn("getApplicationIcon(pkg)", editor)
        self.assertIn("SlotIconCatalog.LABELS", editor)
        self.assertIn("AccentPalette.baseColor(value)", palette)
        self.assertIn("TimePickerDialog", settings)
        self.assertIn("setSingleChoiceItems", settings)
        self.assertIn('setHint("Search apps")', picker)
        self.assertIn("R.drawable.ic_mic", picker)
        self.assertNotIn("androidx.preference", settings)

    def test_media_selection_is_deterministic_radio_separate_and_controls_are_bootstrapped(self):
        prefs = self.read("launcher/src/main/java/com/cbkii/ts18launcher/LauncherPrefs.java")
        media = self.read("launcher/src/main/java/com/cbkii/ts18launcher/MediaListenerService.java")
        launcher = self.read("launcher/src/main/java/com/cbkii/ts18launcher/LauncherActivity.java")
        bootstrap = self.read("launcher/src/main/java/com/cbkii/ts18launcher/MediaSourceBootstrapper.java")
        adapter = self.read("launcher/src/main/java/com/cbkii/ts18launcher/MediaSourceAdapter.java")
        policy = self.read("launcher/src/main/java/com/cbkii/ts18launcher/MediaCommandPolicy.java")
        settings = self.read("launcher/src/main/java/com/cbkii/ts18launcher/SettingsActivity.java")
        radio = self.read("launcher/src/main/java/com/cbkii/ts18launcher/RadioProvider.java")
        self.assertIn('MEDIA_MODE_AUTO = "auto"', prefs)
        self.assertIn('MEDIA_MODE_PREFER_MUSIC = "prefer_music"', prefs)
        self.assertIn("preferConfigured", media)
        self.assertIn("pickExactPackage(controllers, preferredPackage)", media)
        self.assertIn("RadioProvider.resolvePackage(this)", media)
        self.assertIn("sessionDiagnostics", media)
        self.assertIn("MEDIA_REFRESH_INTERVAL_MS = 1000L", launcher)
        self.assertIn("setMediaButtonsReady(radioPrevious, radioPlayPause, radioNext)", launcher)
        self.assertIn("setMediaButtonsReady(mediaPrevious, playPause, mediaNext)", launcher)
        self.assertIn("warmConfiguredSources", launcher)
        self.assertIn("scheduleMediaReadiness()", launcher)
        self.assertIn("onWindowFocusChanged(boolean hasFocus)", launcher)
        self.assertIn("mediaText.setClickable(false)", launcher)
        self.assertNotIn("openCurrentMedia()", launcher)
        self.assertIn("COMMAND_TIMEOUT_MS = 4500L", bootstrap)
        self.assertIn("BROWSER_CONNECT_TIMEOUT_MS = 3000L", bootstrap)
        self.assertIn("ACK_TIMEOUT_MS = 1600L", bootstrap)
        self.assertIn("MediaSourceAdapter.resolve", bootstrap)
        self.assertIn("MediaCommandPolicy.resolve", bootstrap)
        self.assertIn("RootShell.runMillis", bootstrap)
        self.assertIn("Process.myUserHandle().getIdentifier()", bootstrap)
        self.assertIn("awaitAcknowledgement", bootstrap)
        self.assertNotIn("fallbackLaunch", bootstrap)
        self.assertNotIn("startActivity(", bootstrap)
        self.assertNotIn("AppResolver", bootstrap)
        self.assertIn('MEDIA_BROWSER_ACTION = "android.media.browse.MediaBrowserService"', adapter)
        self.assertIn('MEDIA3_SESSION_ACTION = "androidx.media3.session.MediaSessionService"', adapter)
        self.assertIn('NAVRADIO_SERVICE = "com.navimods.radio.RadioService"', adapter)
        self.assertIn('STOCK_TW_RADIO_PACKAGE = "com.tw.radio"', adapter)
        self.assertIn("Stock TW Radio has no qualified background control route", adapter)
        self.assertIn("passiveWarmSafe", adapter)
        self.assertIn("rootStartCommand(int userId)", adapter)
        self.assertIn("enum Phase", policy)
        self.assertIn("controllerReadyForPlay", policy)
        self.assertIn("Generic media selection", settings)
        self.assertIn("Media session diagnostics", settings)
        self.assertIn('NAVRADIO_PLUS_PACKAGE = "com.navimods.radio"', radio)
        self.assertNotIn("sendBroadcast", radio)
        self.assertNotIn("su -c", radio)

    def test_topway_adapter_does_not_guess_stock_radio_contract(self):
        topway = self.read("launcher/src/main/java/com/cbkii/ts18launcher/platform/TopwayAdapter.java")
        self.assertIn('STOCK_MUSIC_PACKAGE = "com.tw.music"', topway)
        self.assertNotIn("STOCK_RADIO_PACKAGE", topway)
        self.assertNotIn("sendBroadcast", topway)
        self.assertNotIn("bindService", topway)

    def test_root_policy_is_bounded_reversible_and_prevalidated(self):
        installer = self.read("scripts/termux/install-standalone-launcher.sh")
        self.assertIn("timeout -k 2", installer)
        self.assertIn("--rollback-home", installer)
        self.assertIn("previous-home.txt", installer)
        self.assertIn("capture_rollback_home_for_change", installer)
        self.assertIn("cmd package resolve-activity", installer)
        self.assertIn("DoFun HOME is not an enabled fallback", installer)

    def test_measurement_reports_partial_capture_and_cleans_partial_archives(self):
        script = self.read("scripts/termux/collect-window-media-evidence.sh")
        self.assertIn("CAPTURE_STATUS=", script)
        self.assertIn("status=PARTIAL", script)
        self.assertIn("rm -f -- \"$zip_tmp\"", script)
        self.assertIn("status=OK", script)

    def test_release_runtime_dependency_and_apk_gates_are_real(self):
        validate = self.read(".github/workflows/validate.yml")
        build = self.read(".github/workflows/build-launcher.yml")
        checker = self.read("tools/launcher_apk_check.py")
        self.assertIn(":launcher:dependencies", validate)
        self.assertIn("releaseRuntimeClasspath", validate)
        self.assertIn("No dependencies", validate)
        self.assertIn("configuration-cache", validate)
        self.assertIn("apksigner verify --verbose", validate)
        self.assertIn("launcher_apk_check.py", validate)
        self.assertIn("launcher_apk_check.py", build)
        self.assertIn("classes.dex", checker)
        self.assertIn("lib/", checker)
        self.assertIn("kotlin/", checker)
        self.assertIn("androidx/", checker)

    def test_candidate_workflow_keeps_write_permission_in_publish_job(self):
        workflow = self.read(".github/workflows/release-candidate.yml")
        self.assertIn("contents: write", workflow)
        self.assertIn("GH_REPO: ${{ github.repository }}", workflow)
        self.assertNotIn('gh release create \"$tag\" qualified/*', workflow)
        for match in re.finditer(r"uses:\s+([^\s]+)", workflow):
            self.assertRegex(match.group(1), r"@(?:[0-9a-f]{40})$")


if __name__ == "__main__":
    unittest.main()
