#!/data/data/com.termux/files/usr/bin/bash
# PR #11 exact-TS18 navigation-surface qualification. Non-interactive; stationary use only.
set -u
OUT_BASE=/storage/emulated/0/Download;EXPECT_PACKAGE="";PHASE=baseline;CAP_TIMEOUT=8;SETTLE=3;LAUNCHER=com.cbkii.ts18launcher;DOFUN=com.dofun.variety;HELPER=/data/adb/ts18-launcher/nav-window.sh;FAILS=0;BLOCKED=0;WARNS=0;LIVE_PID=""
usage(){ echo "Usage: $0 [--expect-package PKG] [--phase baseline|reverse|post-reboot|post-coldboot|post-acc] [--out-base DIR]"; }
while [ "$#" -gt 0 ];do case "$1" in --expect-package)EXPECT_PACKAGE="${2:-}";shift 2;;--phase)PHASE="${2:-}";shift 2;;--out-base)OUT_BASE="${2:-}";shift 2;;-h|--help)usage;exit 0;;*)usage >&2;exit 64;;esac;done
case "$PHASE" in baseline|reverse|post-reboot|post-coldboot|post-acc);;*)exit 64;;esac;case "$EXPECT_PACKAGE" in ''|*[!A-Za-z0-9._]*)[ -z "$EXPECT_PACKAGE" ]||exit 64;;esac
STAMP="$(date +%Y%m%d-%H%M%S 2>/dev/null||printf unknown)";OUT="$OUT_BASE/TS18-PR11-nav-$PHASE-$STAMP";ZIP="$OUT.zip";mkdir -p "$OUT"/{identity,packages,window,logs,screens,topway}||exit 1;printf 'time\tstatus\tcheck\tdetail\n'>"$OUT/results.tsv"
log(){ printf '[%s] %s\n' "$(date +%H:%M:%S 2>/dev/null||printf --:--:--)" "$*"|tee -a "$OUT/run.log"; }
result(){ status="$1";check="$2";detail="$3";printf '%s\t%s\t%s\t%s\n' "$(date +%H:%M:%S 2>/dev/null||printf --:--:--)" "$status" "$check" "$detail">>"$OUT/results.tsv";log "$status $check :: $detail";case "$status" in FAIL)FAILS=$((FAILS+1));;BLOCKED)BLOCKED=$((BLOCKED+1));;WARN)WARNS=$((WARNS+1));;esac; }
have(){ command -v "$1">/dev/null 2>&1; }
capture(){ rel="$1";shift;mkdir -p "$(dirname "$OUT/$rel")";timeout -k 2 "$CAP_TIMEOUT" "$@">"$OUT/$rel" 2>&1||printf '\n[capture] exit=%s\n' "$?">>"$OUT/$rel"; }
capture_sh(){ rel="$1";shift;capture "$rel" sh -c "$*"; }
root_capture(){ rel="$1";shift;mkdir -p "$(dirname "$OUT/$rel")";[ "$ROOT_OK" -eq 1 ]||{ echo 'BLOCKED: root unavailable'>"$OUT/$rel";return;};timeout -k 2 "$CAP_TIMEOUT" su -c "$*">"$OUT/$rel" 2>&1||printf '\n[root capture] exit=%s\n' "$?">>"$OUT/$rel"; }
screenshot(){ [ "$ROOT_OK" -eq 1 ]&&timeout -k 2 5 su -c 'screencap -p /sdcard/Download/.pr11-shot.png'>/dev/null 2>&1&&cp /sdcard/Download/.pr11-shot.png "$OUT/screens/$1.png" 2>/dev/null||true; }
stop_log(){ [ -n "$LIVE_PID" ]&&kill "$LIVE_PID" 2>/dev/null||true;LIVE_PID=""; }
finalize(){ rc=$?;trap - EXIT INT TERM HUP;stop_log;printf 'fails=%s\nblocked=%s\nwarns=%s\nphase=%s\n' "$FAILS" "$BLOCKED" "$WARNS" "$PHASE">"$OUT/summary.txt";if have sha256sum;then (cd "$OUT"&&find . -type f ! -name SHA256SUMS.txt -print0|sort -z|xargs -0 -r sha256sum)>"$OUT/SHA256SUMS.txt" 2>/dev/null||true;fi;rm -f "$ZIP";have zip&&(cd "$(dirname "$OUT")"&&zip -qr "$ZIP" "$(basename "$OUT")")||true;printf 'Evidence: %s\n' "$OUT";[ -f "$ZIP" ]&&printf 'Archive: %s\n' "$ZIP";exit "$rc";};trap finalize EXIT INT TERM HUP
have timeout||{ result FAIL prerequisite 'Termux timeout missing';exit 2; };ROOT_OK=0;if have su&&[ "$(timeout -k 1 4 su -c 'id -u' 2>/dev/null|tail -n1)" = 0 ];then ROOT_OK=1;result PASS root uid0;else result BLOCKED root unavailable;fi
if have logcat;then logcat -v threadtime -s TS18Nav:I ActivityTaskManager:I ActivityManager:I WindowManager:I >"$OUT/logs/live.log" 2>&1&LIVE_PID=$!;fi
capture identity/date.txt date -Ins;capture identity/wm-size.txt wm size;capture identity/wm-density.txt wm density;capture identity/home.txt sh -c 'cmd package resolve-activity --brief -a android.intent.action.MAIN -c android.intent.category.HOME 2>&1||true';capture packages/launcher.txt dumpsys package "$LAUNCHER";capture packages/dofun.txt dumpsys package "$DOFUN";for pkg in app.organicmaps.incar com.google.android.apps.maps net.osmand net.osmand.plus com.sygic.aura;do capture "packages/$pkg.txt" dumpsys package "$pkg";done
root_capture packages/launcher-prefs.xml 'cat /data/user/0/com.cbkii.ts18launcher/shared_prefs/ts18_launcher.xml 2>/dev/null||cat /data/data/com.cbkii.ts18launcher/shared_prefs/ts18_launcher.xml 2>/dev/null||true';root_capture topway/state.txt 'for p in persist.tw.forcepip sys.tw.forcepip sys.tw.forcepip.x sys.tw.forcepip.y sys.tw.forcepip.w sys.tw.forcepip.h sys.df.desktop sys.df.variety.theme.window;do printf "%s=" "$p";getprop "$p";done;for f in /data/tw/custom_pip_app_name /data/tw/navi_name;do printf "%s=" "$f";cat "$f" 2>/dev/null||printf unreadable;printf "\n";done'
TARGET="$EXPECT_PACKAGE";MODE=unknown;if [ -s "$OUT/packages/launcher-prefs.xml" ];then prefs="$OUT/packages/launcher-prefs.xml";found="$(sed -n 's/.*<string name="app.navigation">\([^<]*\)<\/string>.*/\1/p' "$prefs"|tail -n1)";[ -n "$found" ]&&TARGET="$found";foundmode="$(sed -n 's/.*<string name="navigation.surface.mode">\([^<]*\)<\/string>.*/\1/p' "$prefs"|tail -n1)";if [ -n "$foundmode" ];then MODE="$foundmode";elif grep -q '<boolean name="map.enabled" value="true"' "$prefs";then MODE=leaflet;else MODE=fullscreen;fi;fi;[ -n "$TARGET" ]||{ pm path app.organicmaps.incar >/dev/null 2>&1&&TARGET=app.organicmaps.incar;};printf '%s\n' "$TARGET">"$OUT/selected-package.txt";printf '%s\n' "$MODE">"$OUT/selected-mode.txt";[ -n "$TARGET" ]&&result PASS selected-package "$TARGET"||result FAIL selected-package none;result PASS selected-mode "$MODE";[ -z "$EXPECT_PACKAGE" ]||[ "$TARGET" = "$EXPECT_PACKAGE" ]||result FAIL expected-package "expected=$EXPECT_PACKAGE actual=$TARGET"
[ "$ROOT_OK" -eq 1 ]&&timeout -k 2 5 su -c 'input keyevent 3'>/dev/null 2>&1||true;sleep "$SETTLE";screenshot home;capture window/activity-home.txt dumpsys activity activities;capture window/windows-home.txt dumpsys window windows;capture_sh window/focus-home.txt "dumpsys activity activities 2>&1|grep -Ei 'mResumedActivity|topResumedActivity|TaskRecord|windowingMode|mBounds|$LAUNCHER|$TARGET'||true"
if [ "$MODE" = raw_freeform ]||[ "$MODE" = android_pip ];then if [ "$ROOT_OK" -ne 1 ];then result BLOCKED helper-status root-unavailable;elif [ ! -x "$HELPER" ];then result FAIL helper-status "helper not staged: $HELPER";else root_capture window/helper-status.txt "$HELPER status $TARGET 0";line="$(grep -E '^(OK|FAIL) ' "$OUT/window/helper-status.txt"|tail -n1)";case "$line" in OK*)wm="$(printf '%s\n' "$line"|sed -n 's/.* windowingMode=\([^ ]*\).*/\1/p')";display="$(printf '%s\n' "$line"|sed -n 's/.* display=\([^ ]*\).*/\1/p')";component="$(printf '%s\n' "$line"|sed -n 's/.* component=\([^ ]*\).*/\1/p')";expected=5;[ "$MODE" = android_pip ]&&expected=2;if [ "$display" = 0 ]&&[ "$wm" = "$expected" ]&&printf '%s' "$component"|grep -q "^$TARGET/";then result PASS task-state "mode=$wm display=$display component=$component";else result FAIL task-state "$line";fi;;FAIL*)result FAIL helper-status "$line";;*)result FAIL helper-status no-protocol-line;;esac;fi;else result PASS task-state "mode=$MODE has no foreign embedded-task requirement";fi
if [ "$ROOT_OK" -eq 1 ]&&{ [ "$MODE" = raw_freeform ]||[ "$MODE" = android_pip ];};then screenshot before-map-input;timeout -k 2 5 su -c 'input swipe 650 360 700 360 250'>/dev/null 2>&1&&result INFO map-gesture 'input dispatched; compare screenshots'||result WARN map-gesture failed;sleep 1;screenshot after-map-input;fi
if [ "$PHASE" = reverse ];then result INFO reverse 'engage/release reverse during next 20 seconds';sleep 20;screenshot post-reverse;fi
capture window/activity-final.txt dumpsys activity activities;capture window/windows-final.txt dumpsys window windows;capture_sh logs/relevant.txt "logcat -d -v threadtime -t 1600 2>&1|grep -Ei 'TS18Nav|isPipLauncher|sendNaviType|forcepip|$LAUNCHER|$TARGET|ActivityTaskManager|WindowManager'||true";stop_log
cat >"$OUT/README.txt" <<EOF
PR #11 navigation-surface evidence: mode=$MODE target=$TARGET phase=$PHASE
Raw freeform shell PASS requires mode 5; Android PiP shell PASS requires mode 2. Neither proves the HOME goal.
Manually confirm map visible in intended rectangle, HOME visible, map input, launcher input outside it, fullscreen/HOME coherence.
PiP may legitimately prove glance-only. BLOCKED is dependency-blocked, not absence. Topway state is read only.
EOF
[ "$FAILS" -gt 0 ]&&exit 2;[ "$BLOCKED" -gt 0 ]&&exit 3;exit 0
